---
title: "Syllabus"
subtitle: "Principles of Data Science"
format:
  html:
    email-obfuscation: javascript
  pdf: 
    fontfamily: tgpagella
    fontenc: T1
---

<!-- ::: {.content-visible when-format="html"} -->
<!-- | {{< fa file-pdf title="Download" >}} [Download Syllabus](https://padlab.ucr.edu/Franchak_cv.pdf)  -->
<!-- ::: -->

### Instructors
:::: {.grid .course-details .course-details-smaller}

::: {.g-col-18 .g-col-sm-8 .g-col-md-4}
- [{{< fa user >}}]{.fa-li} [{{< var instructor.name >}}]({{< var instructor.url >}})
- [{{< fa university >}}]{.fa-li} {{< var instructor.office >}}
- [{{< fa envelope >}}]{.fa-li} <a href='mailto:{{< var instructor.email >}}'>{{< var instructor.email >}}</a>
- [{{< fa brands github >}}]{.fa-li} <a href='https://github.com/{{< var instructor.github >}}'>{{< var instructor.github >}}</a>
- [{{< fa calendar-check >}}]{.fa-li} [Schedule an appointment]({{< var instructor.appointment_url >}})
:::

::: {.g-col-18 .g-col-sm-8 .g-col-md-4}
- [{{< fa user >}}]{.fa-li} [{{< var instructor2.name >}}]({{< var instructor2.url >}})
- [{{< fa university >}}]{.fa-li} {{< var instructor2.office >}}
- [{{< fa envelope >}}]{.fa-li} <a href='mailto:{{< var instructor2.email >}}'>{{< var instructor2.email >}}</a>
- [{{< fa brands github >}}]{.fa-li} <a href='https://github.com/{{< var instructor2.github >}}'>{{< var instructor2.github >}}</a>
- [{{< fa calendar-check >}}]{.fa-li} {{< var instructor2.office_hrs >}}
:::

::::

::: {.course-details .course-details-smaller}
### Course details

- [{{< fa calendar-alt >}}]{.fa-li} {{< var course.dates >}}
- [{{< fa calendar >}}]{.fa-li} {{< var course.days >}}
- [{{< fa clock >}}]{.fa-li} {{< var course.time >}}
- [{{< fa compass >}}]{.fa-li} {{< var course.location >}}
:::

# Course Description

Most quantitative courses (importantly) focus on the final steps of data analysis---conducting and understanding statistical tests. However, much of the work in data science is taking raw data, often from multiple, incompatible sources, and processing those data into a usable form. This course will emphasize the importance of robust, documented, and automated workflows for processing data to save time, reduce errors, improve reproducibility, and facilitate collaboration among multiple researchers. We will also spend time on data visualization and communication---an important part of creating, checking, and collaborating on data workflows. We will use the R programming language, Github, and Quarto to work through examples, but the focus is on concepts/best practices that can be applied to any software or programming language. The course is open to students who have little programming experience or experience with R. The goal is for students at all levels of programming experience to set goals to improve their data science skills. 

The goals of this course are for you to critically analyze and improve your data analysis workflows. Implementing robust, automated procedures for handling data will allow you to:

- Foster open science through increased transparency, reproducibility, and easier data sharing
- Increase the fidelity of your data and analyses by detecting and preventing errors
- Better understand and communicate about your data
- Save time by preventing errors, automating tasks, and reusing code
- Facilitate collaboration with organized and documented workflows

# Course Materials

- The course [website](index.qmd) has the schedule, lectures, and assignments.
- The [Github page](https://github.com/orgs/2026-PSYC-259/repositories) has all of the code repositories that we cover, and the source code for this website.
- Readings from *R for Data Science* are available [online](https://r4ds.hadley.nz/).
- PDFs of other course readings are linked from the [schedule](schedule.qmd) and lectures
- Other helpful [resources](resources.qmd) are compiled for your future reference.

# Assignments and Grading

Grading for the class is S/NC. A grade of 80% is needed to pass the class. Your grade will be based on the following:

|Component|Weight|
|:--------|:------|
|Participation           | 20%|
|Weekly assignments      | 30%|
|Workflow critique       | 20%|
|Final project           | 30%|


### Participation 

You are expected to attend each class and participate in class discussions. Readings should be completed prior to class so that you are prepared. 

### Weekly Assignments 

We will assign short practical assignments after most weeks of class. These exercises will develop your skills in R programming and other concepts that we discuss. You are allowed to work in groups of 2-3 students to complete these exercises if you would like, but each student should turn in their own assignment. Please indicate in the top of your assignment the names of the students you worked with. Some class time will be given so that you can start work on the assignment with the help of the instructors.  

### Workflow Self-Critique 

You should choose a current or past data analysis project that you have worked with (or one from your lab if you are a newer student). In a class presentation during week 5, 6 or 8, you will  describe the end-to-end workflow of your data. What are sources of raw data? How are those sources combined and/or processed? What research personnel, computing resources, software, and hardware devices are involved? What is the end product needed for statistical analysis? Next, you will take a critical eye to your workflow and identify 1) Where are errors most likely to occur, 2) What time-consuming steps could be automated, and 3) how your workflow could be made more transparent and reproducible.

### Final Project 

In your final project, you will improve the data workflow that you chose using skills learned in this class. Your final project should be shared with the instructor and TA through an online repository (such as Github, OSF, or Code Ocean) and allow your end-to-end data workflow to be reproduced (e.g., include raw data files, functions that implement processing steps, etc.). You can use whatever programming languages are necessary (it doesn't need to just be in R), but you should consult with the instructor if R will not be used to ensure that the instructor can run your code (or alternatively, that you demonstrate your workflow to the instructor). Your project should be a report, either to demonstrate exploratory analyses or to communicate the results, that is written in Quarto and contains visualizations written in R. 

# Course Policies

Keep an eye on this course [website](index.qmd) for updates to the syllabus and materials. We will communicate changes through email and/or Canvas announcements. 

## Attendance

In the event of absences due to illness or family obligations, please contact the instructors immediately so that we can make arrangements. Everyone is in a different situation, so we will always work with you to figure out a way to handle sustained disruptions to learning. You will be responsible for knowing information (e.g., course material and announcements) discussed in class during any absence. We suggest getting at least two of your classmates’ contact information to determine what you missed during any absence and to obtain complete lecture notes. 

## Withdrawal

If you want to withdraw from the course, you are responsible for meeting UCR’s [deadlines](https://registrar.ucr.edu/calendar).

## Artificial Intelligence (AI)

Generative AI (such as Google Gemini or ChatGPT) can be a potentially useful and powerful information source which can enhance productivity and learning. However, over-reliance or dependence on generative AI can undermine your education, limit opportunities for intellectual growth, and impact your performance in venues like job interviews, meetings, and presentations. **Importantly, for courses in quantitative methods, overreliance on AI for learning statistical coding can result in serious errors in data analysis that could potentially have implications for scientific conclusions up to and including the need to retract published work.** Therefore, this course has been designed to emphasize authentic learning and utilizes assessment methods that reduce the potential usefulness of generative AI in your work. Furthermore, all work submitted in this course must be your own. Although generative AI may be used like any other source of information that supports your work (such as a book, article, video, interview, etc.), it must be properly quoted and cited each time it is used. Failure to properly cite the use of AI in your work will be viewed as a potential academic integrity violation. If you have used generative AI for any part of your problem sets or course project, you must include a statement and citation at the beginning of the document.

## Academic Integrity Policy

Academic honesty is expected of all students in all situations including, but not limited to, examinations, assignments, papers, laboratory work, academic transactions, and records. UCR’s [Academic Integrity policy](https://conduct.ucr.edu/policies/academic-integrity-policies-and-procedures) holds students to a code of conduct with which you should familiarize yourself. This policy specifies a range of sanctions from which faculty can choose when violations occur. All UCR students, including those enrolled in this course, are held to the standards in the policy. For example, any form of dishonesty/lying/fabrications (for instance, falsely claiming you were ill or that a relative passed away to receive an extension on a due date, falsely claiming that you submitted an assignment, falsely claiming internet or computer failure, falsifying doctors’ notes), falsifying records, cheating, plagiarism, inappropriate collaboration, or the facilitation of academic dishonesty will result in disciplinary action. We follow a zero tolerance policy on academic dishonesty. Acts of academic dishonesty could result in grades being withheld for a course or suspension from your academic program. Other potential sanctions may include loss of registration privileges, or disqualification and dismissal.

## Students with Disabilities

Reasonable and appropriate accommodations will be made for students with documented disabilities who have arrangements with the Student Disability Resource Center. Students who feel they will need accommodations in this class but have not registered with the [Student Disability Resource Center (SDRC)](https://sdrc.ucr.edu/) should contact SDRC immediately. The SDRC office is located on the first floor of the Student Services Building. SDRC staff can also be reached at: (951) 827-3861. It is your responsibility to inform us that you require testing accommodations, laboratory accommodations (i.e., for the software portion of the class), note-taking services, interpreting services, or alternative formats within the first week of class. If you require note-taking services, you will only receive notes for class lectures that you have attended or for which you have an excused absence. You will not receive notes for lectures that were missed due to an unexcused absence. 

## Prohibition Against Discrimination, Harassment, and Retaliation

Title IX is a federal law that provides that no person be excluded on the basis of sex from participation in, be denied benefits of, or be subjected to discrimination under any education program or activity.  Both [Title IX and university policy](https://titleix.ucr.edu/) make clear that sexual violence and harassment based on sex is prohibited. An individual who believes they have been subjected to sexual violence or harassment can seek support, including counseling and academic support, from the university.

As mandated reporters, we are obligated to report any information we become aware of regarding alleged acts of sexual discrimination, including sexual violence and dating violence. [UCR Counseling & Psychological Services](https://counseling.ucr.edu/) is available if you wish to discuss any concerns confidentially and privately.

## Policy against Threatening Behavior

Please review UCR policy and procedures regarding disruptive, threatening, or violent individuals on campus [here](https://policyking.ucr.edu/home/policy/6539d1030ad0f868b866376b).
Students, faculty, staff, and other individuals do not have an unqualified right of access to university grounds, property, or services. Interfering with the peaceful conduct of university-related business or activities or remaining on campus grounds after a request to leave may be considered a crime. All incidents and allegations of violent or threatening conduct by a UCR student (whether on- or off-campus) must be reported to the UCR Police Department and the Dean of Students. If either office determines that the behavior poses or has posed a serious threat to personal safety or to the welfare of the campus, the student will not be permitted to return to campus or reside in any UCR residence hall until an appropriate threat assessment has been completed and, if necessary, conditions for return are imposed. The UCR Police Department, the Dean of Students, and other appropriate offices will coordinate the assessment in light of the relevant circumstances.

## Counseling Services

[UCR Counseling & Psychological Services](https://counseling.ucr.edu/) provides confidential personal counseling and crisis services for students experiencing emotional concerns, difficulties adjusting, and other factors that affect their ability to achieve their academic and personal goals. For more information, call 951-827-5531. For the 24-hour crisis hotline, call 951-827-5531, option 1. 

## Content Warning

Lectures and assignments may contain language or references to topics that some students may find offensive. Please inform me if you are concerned about the content so that alternative arrangements can be made.

## Copyright and Recording

Do not sell, copy, post online, or otherwise distribute material from this course. The copyright protection of spoken words rests in common law. Copyright regarding notes or other written or recorded works is statutory. Please consult with me for permission before recording lectures (audio or video). Each student must refrain from uploading to any course shell, discussion board, or website used by the course instructor or other course forums, material that is not the student's original work, unless the student first complies with all applicable copyright laws. I reserve the right to delete materials on the grounds of suspected copyright infringement. The course content, including lectures, are copyrighted materials. Students may not share outside the class, upload, sell, or distribute course content or notes taken during the conduct of the course without my permission.

**Please refer to the [UCR policies website](https://deanofstudents.ucr.edu/policies-procedures/documents) for additional policy information.**

