---
title: "Setting up your coding environment"
---

## Setting up R, RStudio, Git, and Github

Although you can use lab computers with RStudio and R already installed, it's most useful for you to get comfortable with running everything on your own system. Follow these instructions to setup the software environment we will need for this class. These instructions are adapted from  [Happy Git](https://happygitwithr.com).

### Install R and R Studio

Install a pre-compiled binary of R for your operating system from [CRAN](https://cloud.r-project.org). Make sure you pick the right version for Apple silicon (M1, M2, etc.) versus Intel Macs.

Install [RStudio Desktop](https://www.rstudio.com/products/rstudio/download/preview/).

For details about checking already-installed software, check [these instructions](https://happygitwithr.com/install-r-rstudio.html#install-r-rstudio).

### Install Git and GitHub

Follow the directions [here](https://happygitwithr.com/install-git.html) install git on either Windows or Mac.

Create a free [GitHub account](https://github.com) (if you don't already have one). This will be a public-facing name and something you might use for a long time, so choose a sensible name.

Install the GitHub [Desktop client](https://desktop.github.com/). 

### Test out Github

Follow the "Hello, World" Tutorial [here](https://guides.github.com/activities/hello-world/). This uses GitHub only (without messing around with local files on your computer or through RStudio, but it's a good introduction to some of the key functions). 
